### ISSUE TITLE
libmySQL.dll is a virus?!

### ISSUE THREAD

**Issue by dezlov** [flakron-shkodra/LazSqlX#3]
The `libmySQL.dll` file which comes bundled with LazSqlX is detected as a virus / trojan by a significant number of security vendors. Including the latest MSI marking it as a trojan and deleting it automatically. 

It doesn't look like an official MySQL Connector. What is the source of this library? Can it be updated or replaced?

[VirusTotal reports 11 / 63](https://www.virustotal.com/#/file/dbf6907fd3d00a2924b497f91833e185daaf8de0817b2bfcc003301dce959785/detection):

![libmysql on virustotal](https://user-images.githubusercontent.com/7993917/37825717-af8b7978-2e88-11e8-8ce2-eb6c172eda66.PNG)

**Comment by flakron-shkodra** [comment]
i've replaced the existing libmysql.dll with another secure version wich is also downloaded from internet but resulted free of threats by virustotal, thanks for your report.

**Comment by dezlov** [comment]
Is there a reason why it can't be replaced by the official MySQL library?

MySQL Connector/C (libmysqlclient) for Windows contains `libmysql.dll`.
https://dev.mysql.com/downloads/connector/c/

Either way, it would be useful if you mention the source of all bundled libraries.
